name: Display Name Script
run-name: ${{ github.actor }} is testing GitHub Action
on:
  push:
  workflow_dispatch:
jobs:
  display_name_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Show last and first name
    - run: echo "My first name is Oleh"
    - run: echo "My last name is Rudomin"

     
